# Site settings
title: vfan140's Blog
email: vfan140@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
github_username:  vfan140
encoding: utf-8
# Build settings
markdown: redcarpet
kramdown:
  input: GFM

redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

future:      true
# Amount of posts to show on home page
paginate: 5
